server:
  port: 9012
spring:
  application:
    name: rabbit-consumer
  rabbitmq:
    host: 192.168.80.129
    virtual-host: /test
    username: test
    password: test
    connection-timeout: 10000 #超时时间
    #采用手动应答
    listener:
      simple:
        acknowledge-mode: manual
        #        指示容器是否随着ApplicationContext的启动而启动。
        #        设置这个值为false，如果在你启动的时候消息代理还没有启动，当消息代理准备好的时候调用start()方法手动启动。
        auto-startup: true
        default-requeue-rejected: false #不重回队列
        concurrency: 5 #在初始化监听器的时候，并发消费者的数目。
        max-concurrency: 20 #在初始化监听器的时候，并发消费者的数目最大值。
        prefetch: 1 # 每次只处理一个信息
        retry:
          enabled: true
