server:
  port: 9011
spring:
  application:
    name: rabbitmq-server
  profiles:
    active: dev
  rabbitmq:
    host: 192.168.80.129
    virtual-host: /test
    username: test
    password: test
    ##开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true
    template:
#      当mandatory标志位设置为true时，如果exchange根据自身类型和消息routingKey无法找到一个合适的queue存储消息，
#      那么broker会调用basic.return方法将消息返还给生产者;当mandatory设置为false时，出现上述情况broker会直接将消息丢弃;
#      通俗的讲，mandatory标志告诉broker代理服务器至少将消息route到一个队列中，否则就将消息return给发送者;
      mandatory: true
